# 了解numpy
- numpy的数组和python列表的区别
- 创建numpy数组
- [[100,100],[1],[9]]

In [5]:
import numpy as np

array = np.array([1,2,3,4,5], dtype=np.float64)
print(array)
print(array.ndim)
print(array.dtype)
print(array.shape)
print(array.size)
print(array.itemsize)

[1. 2. 3. 4. 5.]
1
float64
(5,)
5
8


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr1 = np.copy(arr) #deep copy 
print(arr1)
arr2 = arr.copy() #deep copy
print(arr2)
arr3 = arr #shallow copy
arr4 = arr.view() #shallow copy 独立的形状和步幅信息，但是共享数据


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [19]:
'''
从形状或者值创建
'''
# empty 接受shape参数，返回一个新的数组，只分配内存空间但不填充任何值
arr = np.empty(shape=(3,2),dtype=np.int32)
print(arr, '\n',arr.shape,arr.ndim,arr.size,arr.itemsize)
# empty_like 接受一个数组作为参数，返回一个新的数组，只分配内存空间但不填充任何值
'''
arr1 = [[100,100],[1],[9]]
NumPy的数组必须是规则的，也就是说，它们的所有维度都必须有相同的长度。
'''
arr1 = [[100],[1],[9]]
arr2 = np.empty_like(arr1)
print(arr2)
print(arr2.shape,arr2.ndim,arr2.size,arr2.itemsize)
# np.zeros np.zeros_like np.ones np.ones_like
print(np.zeros((5,)))
# np.full np.full_like
print(np.full((2,2),7))
# np.eye 单位矩阵
print(np.eye(2,M=2,k=2,dtype=np.int32))

[[100   0]
 [  1   0]
 [  9   0]] 
 (3, 2) 2 6 4
[[100]
 [  1]
 [  9]]
(3, 1) 2 3 8
[0. 0. 0. 0. 0.]
[[7 7]
 [7 7]]
[[0 0]
 [0 0]]


In [25]:
'''
从数值范围创建numpy数组
'''
arr = np.arange(10,20,2,np.int32) # 10-19 步长为2
print(arr)
print(arr.ndim,arr.shape,arr.size,arr.itemsize)
# np.linspace 等差数列 返回元组(np.array,step)
arr = (np.linspace(10,20,5,True,True,np.float64)) # 10-20 5个数
print(arr[0].ndim)

[10 12 14 16 18]
1 (5,) 5 4
1


In [29]:
'''
基本元算
'''

arr = [[1,2],[3,4]]
arr2 = [[5,6],[7,8]]
arr = np.array(arr)
arr2 = np.array(arr2)
print(arr > 2,'\n')
print(arr + 2,'\n')
print(arr - 2,'\n')
print(arr * 2,'\n')
print(arr + arr2,'\n')
print(arr - arr2,'\n')
print(arr * arr2,'\n')
print(arr / arr2,'\n')
print(arr > arr2,'\n')

[[False False]
 [ True  True]] 

[[3 4]
 [5 6]] 

[[-1  0]
 [ 1  2]] 

[[2 4]
 [6 8]] 

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[False False]
 [False False]] 



In [33]:
'''
广播机制
NumPy的广播机制是一种强大的功能，它允许在不同形状的数组之间进行数学运算。

广播的规则如下：

1. 如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补1。

2. 如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状将沿着维度为1的维度扩展以匹配另外一个数组的形状。

3. 如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于1，那么会引发异常。

例如，假设我们有一个1D数组和一个2D数组：

```python
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
```

我们可以将`a`和`b`相加，即使它们的形状不同。这是因为NumPy会将`a`的形状扩展为`(3, 3)`，然后进行相加：

```python
c = a + b
```

结果`c`是一个形状为`(3, 3)`的2D数组：

```python
array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])
```

这就是NumPy的广播机制。它使得我们可以方便地对不同形状的数组进行数学运算。
'''

a = np.array([0,1,0])
b = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a.shape)
print(b.shape)
print(a + b)
print(np.arange(2*3*4).reshape(2,3,4))

(3,)
(3, 3)
[[0 2 2]
 [3 5 5]
 [6 8 8]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [60]:
'''
索引和切片
数组的索引和切片与 Python 中序列的索引和切片操作基本类似，不同点在于：
数组切片不会复制内部数组数据，只会生成原始数据的新视图
数组还支持多维数组的多维索引和切片，以及高级索引操作
'''
# 基本索引和切片
arr = np.arange(10).reshape(2,5)
print(arr)
print()
print(arr[1,2])
print()
print(arr[1:2,2:3])

# 高阶索引
# 把整数列表或者bool数组作为索引
print()
arr = np.arange(24).reshape(3,2,4)
print(arr)
print()
# print(arr[[2,0,0]].shape) #可以理解为按照索引数组的顺序，将原数组的元素拼接起来，arr[2] + arr[0] + arr[0]
# print()
# print(arr[[2,0,1],[1,1,0]]) # arr[2,1] + arr[0,1] + arr[1,0]
# print()
# print(arr[[2,0,1],:,[1,1,0]]) # arr[2,:,1] + arr[0,:,1] + arr[1,:,0]
# print()
# print(arr[[2,0,1],[1,0,1],[0,0,1]])
# print()
print(arr[0, [0, 0, 1], [1, 2, 3]]) # 基本索引和高级索引组合使用，小维度数组的形状会广播
print()
print(arr[[0],[0,0,1],[1,2,3]]) # 基本索引和高级索引组合使用，小维度数组的形状会广播

[[0 1 2 3 4]
 [5 6 7 8 9]]

7

[[7]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

[1 2 7]

[1 2 7]


In [54]:
'''
bool数组作为索引
'''

arr = np.arange(24).reshape(3,2,4)
# arr1 = arr % 2 == 0
# print(arr[np.array(arr1)])
arr1 = [[[True,False,False,True],[True,False,False,True]],
        [[True,False,False,True],[True,False,False,True]],
        [[True,False,False,True],[True,False,False,True]]]
print(arr[arr1])
arr2 = [[True,False],[True,False],[True,False]]
print(arr[arr2])

[ 0  3  4  7  8 11 12 15 16 19 20 23]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]


In [59]:
'''
基本切片和高级索引混合
'''
x = np.arange(48).reshape((2, 2, 3, 4))
print(x)
""" 只有一个高阶索引, 不存在分隔 """
arr1 = x[0:1, 0:1, 0:1, [0, 1]]
arr2 = x[[0,0],[0,0],[0,0],[0,1]]
print(arr1.shape,arr1.ndim)
print(arr2.shape,arr2.ndim) # x[0,0,0,0] + x[0,0,0,1]

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
(1, 1, 1, 2) 4
(2,) 1


In [94]:
'''
常用函数
'''

arr = np.arange(8).reshape(2,2,2)
arr1 = np.array([
    [[3,3],[3,5]],
    [[3,3],[3,5]],
    ])
# print(arr)
# print()
# print(arr1)
# print()
# print(arr.T)
# print(arr.squeeze())
# # print(np.squeeze(arr,1))
# print()
'''
点积的条件：
一维：a[0]*b[0] + a[1]*b[1] + a[2]*b[2] + ...
二维：点积运算等于矩阵乘法。例如，对于两个二维数组A和B，np.dot(A, B)等于一个新的二维数组，它的每个元素都是A的一行和B的一列的点积。
'''
print(np.dot(arr, arr1).shape)

print()
# arr3 = np.array([1,2,3])
# arr4 = np.array([0,1,2])
# print(np.dot(arr3,arr4))
# print()

arr5 = np.array([[[1,2,1,2],[3,4,2,2]],[[1,2,1,2],[3,4,2,2]],[[1,2,1,2],[3,4,2,2]],[[1,2,1,2],[3,4,2,2]],[[1,2,1,2],[3,4,2,2]],[[1,2,1,2],[3,4,2,2]]])
# arr6 = np.array([[1,0,1],[0,1,1]])
arr6 = np.arange(16).reshape(2,4,2)
print(arr5.shape)
print(arr6.shape)
print()
# print(np.dot(arr5,arr6))
# print()
'''
在矩阵乘法中，我们将第一个矩阵的行（row）和第二个矩阵的列（column）进行点积运算，以得到结果矩阵的对应元素。
对于二维数组（即矩阵），np.dot和np.matmul的效果是一样的，都是进行矩阵乘法。但是对于高维数组，np.dot和np.matmul的行为是不同的。

np.dot对于高维数组执行的是一个更为通用的点积运算。具体来说，如果你对两个形状为(a, b, ..., m, n)和(c, d, ..., n, p)的数组进行点积运算，那么结果将是一个形状为(a, b, ..., m, c, d, ..., p)的数组。

而np.matmul对于高维数组执行的是一种特殊的乘法运算，它在最后两个维度上进行矩阵乘法，并保持其他维度不变。具体来说，如果你对两个形状为(..., m, n)和(..., n, p)的数组进行矩阵乘法，那么结果将是一个形状为(..., m, p)的数组。

因此，对于高维数组，你应该根据你的具体需求来选择使用np.dot还是np.matmul。
'''
# print(np.matmul(arr5,arr6).shape)
# print(np.dot(arr5,arr6) == np.matmul(arr5,arr6))
print(arr5.dot(arr6))


(2, 2, 2, 2)

(6, 2, 4)
(2, 4, 2)

[[[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]


 [[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]


 [[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]


 [[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]


 [[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]


 [[[ 20  26]
   [ 68  74]]

  [[ 28  39]
   [116 127]]]]
